name: Generate Cyberpunk Data Stream

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Neon SVG Animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#b100e8&color_dots=#ebedf0,#81f0fc,#2be1f5,#05c9df,#009eb0
            dist/github-snake-dark.svg?color_snake=#b100e8&color_dots=#161b22,#063b4d,#096b85,#0b9bbd,#00e5ff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
